Repository legion-platform/legion, pull requests merged in 2018-10, with the labels that each got.

#305 [#301] Fix log storing in small Jenkins
  k8s/jenkins/legion-jenkins-plugin/src/main/resources/legion.groovy
Labels: bug

#532 [#521] CSV writer and reader in S3Hook were fixed
  legion_airflow/legion_airflow/hooks/s3_hook.py
Labels: bug

#528 [#527] Extend Dex config flexibility
  deploy/ansible/roles/k8s_resources/templates/dex.yml.j2
  deploy/helms/dex/templates/secret.yaml
  deploy/profiles/secrets_template.yaml
Labels: feature

#476 [#475] Remove sleeps in regression tests
  tests/python/test_k8s_model_operations.py
  tests/python/test_k8s_properties_storages.py
  tests/python/test_k8s_watching.py
Labels: CI/CD/tests, bug

#547 [#521] Fixed CSV reader to read rows cells with commas and quotes
  legion_airflow/legion_airflow/auth/dex_auth.py
  legion_airflow/legion_airflow/hooks/k8s_base_hook.py
  legion_airflow/legion_airflow/hooks/s3_handler.py
  legion_airflow/legion_airflow/hooks/s3_hook.py
  legion_airflow/tests/test_csv.py
Labels: bug

#515 [#504] Airflow DAGs unable to read credentials from k8s secret
  deploy/helms/airflow/templates/credentials.yaml
  deploy/helms/airflow/templates/worker-rbac.yaml
  legion_airflow/legion_airflow/hooks/k8s_base_hook.py
Labels: bug

#560 [#510] Disabled test that triggers Airflow tasks
  tests/robot/resources/keywords.robot
Labels: bug

#562 [#561] Unify the check of security enabled feature for components
  tests/robot/resources/keywords.robot
Labels: CI/CD/tests, WIP, critical

#522 [#518] [#511] Scale down node after vertical scaling test
  deploy/ansible/roles/k8s_resources/templates/autoscaler.yaml.j2
  deploy/ci-infra.Jenkinsfile
  examples/Vertical-Scaling/performance.Jenkinsfile
  legion_test/legion_test/robot/k8s.py
  legion_test/legion_test/templates/jenkins_performance_job.tmpl
  tests/robot/resources/keywords.robot
  tests/robot/tests/1_common/1.1_check_clusterwide.robot
  tests/robot/tests/2_jenkins_models/2.0_check_jenkins_models.robot
Labels: CI/CD/tests
