Repository legion-platform/legion, pull requests merged in 2018-11, with the labels that each got.

#580 [#579] Fixed healthcheck endpoint in nginx config
  deploy/helms/legion/templates/edge/edge-server.yaml
  k8s/edge/Dockerfile
  k8s/edge/nginx.conf.ltmpl
  legion/legion/template.py
  legion/legion/template_plugins/k8s.py
  legion/legion/template_plugins/os_environ.py
Labels: bug

#587 [#277] Changed Probes for Airflow Web pod, extended timeouts
  deploy/helms/airflow/templates/web.yaml
Labels: bug, critical

#578 [#574] Sign out inactive user after X seconds of inactivity
  deploy/ansible/roles/k8s_resources/templates/oauth2-proxy.yml.j2
  deploy/helms/oauth2-proxy/templates/secret.yaml
  deploy/helms/oauth2-proxy/values.yaml
  deploy/profiles/secrets_template.yaml
Labels: feature, security

#553 [#334][#345] Legionctl '*' tests added, model selector fixed
  legion/legion/k8s/enclave.py
  tests/robot/tests/4_edi_multi_versioned_models/4.0_check_edi_multi_versioned_models.robot
Labels: CI/CD/tests

#588 [#583] Flower scale up and down tests fixed
  legion_test/legion_test/robot/flower.py
  legion_test/legion_test/robot/k8s.py
  tests/robot/tests/1_common/1.3_check_flower.robot
Labels: CI/CD/tests, critical

#589 [#585] Fix unit tests for templates
  legion/tests/test_legion-template.py
Labels: bug

#552 [#546] Extend airflow and jenkins test classes for airflow tests
  legion_test/legion_test/robot/airflow.py
  legion_test/legion_test/robot/jenkins.py
Labels: CI/CD/tests

#603 [#602] Normalize flower tests methods
  legion_test/legion_test/robot/flower.py
  legion_test/legion_test/robot/k8s.py
  tests/robot/resources/keywords.robot
  tests/robot/tests/1_common/1.3_check_flower.robot
Labels: CI/CD/tests, improvement

#551 [#513] Add notifications to Jenkins deploy jobs
  Jenkinsfile
  deploy/ci-app.Jenkinsfile
  deploy/ci-full-lifecycle.Jenkinsfile
  deploy/ci-infra.Jenkinsfile
  deploy/legionPipeline.groovy
Labels: CI/CD/tests

#614 [#613] Count online workers from flower in correct way
  legion_test/legion_test/robot/flower.py
  legion_test/legion_test/robot/k8s.py
Labels: CI/CD/tests, bug, critical

#601 [#270] Fixed S3Hook to work without connection_id
  deploy/ansible/roles/legion_enclave/templates/airflow-values.yaml.j2
  deploy/helms/airflow/templates/configuration.yaml
  legion_airflow/legion_airflow/hooks/s3_handler.py
  legion_airflow/legion_airflow/hooks/s3_hook.py
Labels: bug

#545 [#543] Add EDI unit tests
  deploy/legionPipeline.groovy
  legion/docs/source/testing.md
  legion/legion/config.py
  legion/legion/edi/server.py
  legion/legion/external/edi.py
  legion/legion/http.py
  legion/legion/k8s/enclave.py
  legion/legion/model/client.py
  legion/tests/data/jwt_config/jwt.exp.datetime
  legion/tests/data/jwt_config/jwt.secret
  legion/tests/data/responses/kubernetes.client.CoreV1Api.delete_namespaced_service.V1Status.undeploy_done.json
  legion/tests/data/responses/kubernetes.client.CoreV1Api.list_namespaced_service.V1ServiceList.one_model.json
  legion/tests/data/responses/kubernetes.client.CoreV1Api.list_namespaced_service.V1ServiceList.two_models_1_id_and_2_versions.json
  legion/tests/data/responses/kubernetes.client.ExtensionsV1beta1Api.list_namespaced_deployment.ExtensionsV1beta1DeploymentList.no_models.json
  legion/tests/data/responses/kubernetes.client.ExtensionsV1beta1Api.list_namespaced_deployment.ExtensionsV1beta1DeploymentList.one_model.json
  legion/tests/data/responses/kubernetes.client.ExtensionsV1beta1Api.list_namespaced_deployment.ExtensionsV1beta1DeploymentList.one_model_scaled_to_2.json
  legion/tests/data/responses/kubernetes.client.ExtensionsV1beta1Api.list_namespaced_deployment.ExtensionsV1beta1DeploymentList.two_models_1_id_and_2_versions.json
  legion/tests/data/responses/kubernetes.client.ExtensionsV1beta1Api.list_namespaced_deployment.ExtensionsV1beta1DeploymentList.two_models_scaled_to_2.json
  legion/tests/data/responses/kubernetes.client.ExtensionsV1beta1Api.patch_namespaced_deployment.ExtensionsV1beta1Deployment.last_model_scaled_to_2.json
  legion/tests/data/responses/kubernetes.client.ExtensionsV1beta1Api.patch_namespaced_deployment.ExtensionsV1beta1Deployment.one_model_scaled_to_1.json
  legion/tests/data/responses/kubernetes.client.ExtensionsV1beta1Api.patch_namespaced_deployment.ExtensionsV1beta1Deployment.one_model_scaled_to_2.json
  legion/tests/data/responses/kubernetes.client.apis.apps_v1beta1_api.AppsV1beta1Api.delete_namespaced_deployment.V1Status.last_model_deleted.json
  legion/tests/data/responses/kubernetes.client.apis.apps_v1beta1_api.AppsV1beta1Api.delete_namespaced_deployment.V1Status.model_deleted.json
  legion/tests/legion_test_utils.py
  legion/tests/test_edi.py
  tests/python/test_k8s_model_operations.py
Labels: CI/CD/tests, critical, improvement

#608 [#607] Added S3_BUCKET_NAME env var to Airflow Worker and Jenskins Slave
  deploy/ansible/roles/legion_core_chart/templates/legion-core-values.yaml.j2
  deploy/ansible/roles/legion_enclave/templates/airflow-values.yaml.j2
  deploy/helms/airflow/templates/dags.yaml
  deploy/helms/airflow/templates/worker.yaml
  deploy/helms/airflow/values.yaml
  deploy/helms/legion-core/templates/jenkins/jenkins-server.yaml
  deploy/helms/legion-core/values.yaml
  k8s/jenkins/legion-jenkins-plugin/src/main/resources/legion.groovy
Labels: feature

#612 [#611] Froze python packages versions in Airflow dockerfile
  k8s/airflow/Dockerfile
  legion_test/legion_test/robot/airflow.py
  tests/robot/resources/keywords.robot
Labels: bug, critical

#498 [#479] Remove redundadnt k8s properties changes
  deploy/ansible/roles/legion_enclave/templates/legion-values.yaml.j2
  deploy/helms/legion/templates/metrics/grafana.yaml
  deploy/helms/legion/values.yaml
  deploy/profiles/legion-ci-app.epm.kharlamov.biz.yml
  deploy/profiles/legion-ci-infra.epm.kharlamov.biz.yml
  deploy/profiles/legion-ci.epm.kharlamov.biz.yml
  deploy/profiles/legion-demo.epm.kharlamov.biz.yml
  deploy/profiles/legion-dev.epm.kharlamov.biz.yml
  deploy/profiles/legion-test.epm.kharlamov.biz.yml
  deploy/profiles/profiles_template.yaml
  legion/.pylintrc
  legion/analyze_code.sh
  legion/legion/k8s/__init__.py
  legion/legion/k8s/properties.py
  legion/legion/k8s/utils.py
  legion_test/legion_test/utils.py
  tests/python/test_k8s_introspection.py
  tests/python/test_k8s_model_operations.py
  tests/python/test_k8s_properties_storages.py
  tests/python/test_k8s_watching.py
Labels: bug

#271 [#269] Request size limit in Flask is increased
  deploy/ansible/roles/k8s_resources/templates/ingress-aws.yml.j2
  legion/legion/serving/config_default.py
Labels: bug

#618 [#569] Update requests and notebook packages
  base-python-image/Pipfile
  base-python-image/Pipfile.lock
  k8s/edge/Pipfile
  k8s/edge/Pipfile.lock
Labels: critical, security

#594 [#362] Build doesn't fail with invalid test tags
  deploy/legionPipeline.groovy
Labels: CI/CD/tests, improvement

#622 [#309] Add proxy for jenkins plugins
  Jenkinsfile
  k8s/jenkins/Dockerfile
Labels: CI/CD/tests
