Repository legion-platform/legion, pull requests merged in 2018-07, with the labels that each got.

#203 Fix default value for dex auth backend
  deploy/helms/airflow/values.yaml
Labels: bug

#204 Fix Profile message on slack notification
  deploy/legionPipeline.groovy
Labels: bug

#206 Fix tests for custom profiles location
  deploy/legionPipeline.groovy
  tests/robot/0_check_clusterwide.robot
  tests/robot/1_check_airflow.robot
  tests/robot/2_check_models.robot
  tests/robot/3_check_flower.robot
  tests/robot/4_check_edi.robot
Labels: bug

#221 Fixes Slack notifications for errors on jobs without LocalVersion
  deploy/legionPipeline.groovy
Labels: bug

#213 [#195] models versions tests for EDI
  Jenkinsfile
  k8s/test-bare-model-api/model-1/Dockerfile
  k8s/test-bare-model-api/model-1/app.py
  k8s/test-bare-model-api/model-1/requirements.txt
  k8s/test-bare-model-api/model-2/Dockerfile
  k8s/test-bare-model-api/model-2/app.py
  k8s/test-bare-model-api/model-2/requirements.txt
  legion/docs/source/preparing_development_envinroment.md
  legion_test/legion_test/robot/utils.py
  legion_test/legion_test/test_assets.py
  tests/robot/4_check_edi.robot
  tests/robot/5_check_edi_milti_versioned_models.robot
  tests/robot/load_variables_from_profiles.py
  tests/robot/resources/keywords.robot
  tests/robot/resources/variables.robot
Labels: CI/CD/tests

#225 [#31] Model dependency capturing
  .gitignore
  Jenkinsfile
  base-python-image/requirements.txt
  docker_bootup.py
  k8s/edi/Dockerfile
  k8s/jenkins/legion-jenkins-plugin/src/main/resources/legion.groovy
  legion/analyze_code.sh
  legion/bin/legionctl
  legion/legion/containers/docker.py
  legion/legion/containers/headers.py
  legion/legion/docker_bootup.py
  legion/legion/edi/deploy.py
  legion/legion/edi/wsgi.py
  legion/legion/k8s/utils.py
  legion/legion/serving/wsgi.py
  legion/legion/serving/wsgi_aio.py
  legion/legion/templates/Dockerfile.tmpl
  legion/legion/templates/docker_files/gunicorn/Dockerfile
  legion/legion/templates/docker_files/nginx.conf
  legion/legion/templates/docker_files/supervisord.conf
  legion/legion/templates/docker_files/uwsgi.ini
  legion/legion/templates/docker_files/uwsgi/Dockerfile
  legion/legion/templates/docker_files/uwsgi/app_uwsgi.ini
  legion/legion/utils.py
  legion/requirements/base.txt
  legion/tests/__init__.py
  legion/tests/legion_test_utils.py
  legion/tests/test_deploy.py
  legion/tests/test_k8s.py
  legion/tests/test_model_client.py
  legion/tests/test_models/complex_model/complex_package/__init__.py
  legion/tests/test_models/complex_model/complex_package/submodule.py
  legion/tests/test_models/complex_model/run.py
  legion/tests/test_models/model_with_io_operations/run.py
  legion/tests/test_models/model_with_native/run.py
  legion/tests/test_models/summation_model/run.py
  legion/tests/test_pyserve.py
Labels: feature

#222 [#114] Add robot test tags config for "Deploy legion job"
  deploy/deploy-legion.Jenkinsfile
  deploy/legionPipeline.groovy
Labels: CI/CD/tests, feature

#205 Multiple model endpoints
  .gitignore
  examples/Digit-Recognition/Recognizing digits.ipynb
  examples/Digit-Recognition/performance/test_basic.py
  examples/Digit-Recognition/tests/test_basic.py
  examples/MovieLens/performance/test_basic.py
  examples/MovieLens/surprise.v3.py
  examples/Sklearn-Income/Income-wo-df.ipynb
  examples/Sklearn-Income/Income.ipynb
  examples/Sklearn-Income/performance/test_basic.py
  examples/Test-Summation/Summation.ipynb
  examples/Test-Summation/performance/test_basic.py
  examples/Test-Summation/tests/test_basic.py
  k8s/edge/nginx.conf.ltmpl
  k8s/test-bare-model-api/model-1/app.py
  k8s/test-bare-model-api/model-2/app.py
  legion/docs/source/model_rest_api.md
  legion/legion/containers/docker.py
  legion/legion/containers/headers.py
  legion/legion/edi/deploy.py
  legion/legion/edi/server.py
  legion/legion/io.py
  legion/legion/metrics.py
  legion/legion/model/client.py
  legion/legion/model/model.py
  legion/legion/model/model_id.py
  legion/legion/serving/pyserve.py
  legion/tests/data/sample-archive.zip
  legion/tests/legion_test_models.py
  legion/tests/legion_test_utils.py
  legion/tests/test_base_io_operations.py
  legion/tests/test_deploy.py
  legion/tests/test_metrics.py
  legion/tests/test_model.py
  legion/tests/test_model_client.py
  legion/tests/test_model_container.py
  legion/tests/test_models/complex_model/run.py
  legion/tests/test_models/math_model/run.py
  legion/tests/test_models/model_with_io_operations/run.py
  legion/tests/test_models/model_with_native/run.py
  legion/tests/test_models/summation_model/run.py
  legion/tests/test_pyserve.py
  legion/tests/test_utils_text_operations.py
  tests/robot/4_check_edi.robot
  tests/robot/resources/keywords.robot
Labels: feature

#224 Enable dex auth on enclave grafana ingress
  deploy/ansible/roles/legion_enclave/templates/legion-values.yaml.j2
Labels: feature

#256 [#246] Simplify tag including in tests run
  deploy/legionPipeline.groovy
  legion_test/legion_test/profiler_loader.py
  tests/python/test_k8s_introspection.py
  tests/python/test_k8s_model_operations.py
  tests/python/test_k8s_watching.py
  tests/robot/5_check_edi_milti_versioned_models.robot
Labels: feature

#265 [#264] Fixed profile validator
  deploy/ansible/create-cluster.yml
  deploy/profiles/secrets_template.yaml
Labels: bug

#268 [#247] fix airflow deploy default values
  deploy/helms/airflow/values.yaml
Labels: CI/CD/tests

#273 [#234] Additional test tags to exclude tests with known issues
  deploy/legionPipeline.groovy
  deploy/profiles/legion-test.epm.kharlamov.biz.yml
  docker_bootup.py
  legion/legion/containers/docker.py
  legion_test/legion_test/robot/utils.py
  tests/robot/4_check_edi.robot
  tests/robot/5_check_edi_multi_versioned_models.robot
  tests/robot/resources/keywords.robot
Labels: CI/CD/tests

#284 [#208] Add correct detecting models for undeploy
  legion/bin/legionctl
  legion/legion/edi/deploy.py
Labels: WIP, bug

#279 [#277] Increased Airflow web probes timeout to 2 secs
  deploy/helms/airflow/templates/web.yaml
Labels: bug

#281 [#212] Check legionctl scale value
  legion/legion/external/edi.py
  legion/legion/k8s/enclave.py
  legion/legion/k8s/services.py
Labels: bug

#293 [#290] Grafana dashboard test access fixed
  k8s/test-bare-model-api/model-2/app.py
  legion_test/legion_test/grafana.py
  tests/robot/4_check_edi.robot
  tests/robot/5_check_edi_multi_versioned_models.robot
  tests/robot/resources/keywords.robot
Labels: CI/CD/tests

#295 [#294] Fix Grafana bootstrapping process
  legion_test/legion_test/grafana.py
  legion_test/legion_test/robot/grafana.py
Labels: bug
