Repository legion-platform/legion, pull requests merged in 2018-08, with the labels that each got.

#249 [#216] [#202] Enable Dex SSO on jenkins
  deploy/ansible/roles/legion_core_chart/templates/legion-core-values.yaml.j2
  deploy/helms/legion-core/templates/jenkins/jenkins-secret.yaml
  deploy/helms/legion-core/templates/jenkins/jenkins-server.yaml
  deploy/helms/legion-core/values.yaml
  deploy/legionPipeline.groovy
  k8s/jenkins/plugins.txt
  k8s/jenkins/scripts/install-plugins.sh
  k8s/jenkins/scripts/security.groovy
  legion_test/bin/create_example_jobs
  legion_test/bin/jenkins_dex_client
  legion_test/legion_test/robot/dex_client.py
  legion_test/legion_test/robot/jenkins.py
  legion_test/setup.py
  tests/robot/2_check_models.robot
  tests/robot/resources/keywords.robot
Labels: CI/CD/tests, WIP, feature

#304 [#303] k8s authenticator
  deploy/ansible/roles/k8s_resources/tasks/copy-ca-cert.yaml
  deploy/ansible/roles/k8s_resources/tasks/k8s-authenticator.yaml
  deploy/ansible/roles/k8s_resources/tasks/main.yml
  deploy/ansible/roles/k8s_resources/templates/k8s-authenticator.yml.j2
  deploy/helms/k8s-authenticator/.helmignore
  deploy/helms/k8s-authenticator/Chart.yaml
  deploy/helms/k8s-authenticator/templates/NOTES.txt
  deploy/helms/k8s-authenticator/templates/_helpers.tpl
  deploy/helms/k8s-authenticator/templates/certificates.yaml
  deploy/helms/k8s-authenticator/templates/configmap.yaml
  deploy/helms/k8s-authenticator/templates/deployment.yaml
  deploy/helms/k8s-authenticator/templates/ingress.yaml
  deploy/helms/k8s-authenticator/templates/service.yaml
  deploy/helms/k8s-authenticator/values.yaml
Labels: feature

#337 Fix oauth2-proxy ingress path at values
  deploy/ansible/roles/k8s_resources/templates/oauth2-proxy.yml.j2
Labels: bug

#350 [#349] Fix kubectl context selection
  deploy/ansible/roles/legion_enclave/tasks/create_enclave.yml
Labels: CI/CD/tests, bug

#320 [#270] Fixed S3Hook to load/write logs in S3 properly
  deploy/ansible/roles/legion_core_chart/tasks/main.yml
  deploy/ansible/roles/legion_enclave/tasks/create_enclave.yml
  deploy/ansible/roles/legion_enclave/templates/airflow-values.yaml.j2
  deploy/ansible/roles/legion_enclave/templates/airflow_s3_access_policy.yaml.j2
  deploy/helms/airflow/templates/configuration.yaml
  deploy/profiles/legion-ci.epm.kharlamov.biz.yml
  deploy/profiles/legion-demo.epm.kharlamov.biz.yml
  deploy/profiles/legion-dev.epm.kharlamov.biz.yml
  deploy/profiles/profiles_template.yaml
  legion/docs/source/configuration.md
  legion_airflow/legion_airflow/hooks/s3_hook.py
  legion_airflow/setup.py
Labels: feature

#356 [#296] Persistent volume for Jenkins workspace
  deploy/ansible/roles/aws_resources/tasks/jenkins-volume.yml
  deploy/ansible/roles/aws_resources/tasks/main.yml
  deploy/ansible/roles/k8s_resources/tasks/jenkins-volume.yaml
  deploy/ansible/roles/k8s_resources/tasks/main.yml
  deploy/ansible/roles/k8s_resources/templates/jenkins-volume.yaml.j2
  deploy/ansible/roles/k8s_terminate_cluster/tasks/jenkins-volume.yml
  deploy/ansible/roles/k8s_terminate_cluster/tasks/main.yaml
  deploy/ansible/roles/legion_core_chart/tasks/main.yml
  deploy/ansible/roles/legion_core_chart/templates/legion-core-values.yaml.j2
  deploy/legionPipeline.groovy
  deploy/profiles/legion-ci.epm.kharlamov.biz.yml
  deploy/profiles/legion-demo.epm.kharlamov.biz.yml
  deploy/profiles/legion-dev.epm.kharlamov.biz.yml
  deploy/profiles/profiles_template.yaml
Labels: feature

#354 [#331][#330] Add valid checking in legionctl after legionctl command
  legion/bin/legionctl
  legion/legion/edi/deploy.py
  legion/legion/edi/server.py
  legion/legion/external/edi.py
  legion/legion/http.py
  legion/legion/k8s/definitions.py
  legion/legion/k8s/enclave.py
  legion/legion/utils.py
  tests/robot/4_check_edi.robot
  tests/robot/5_check_edi_multi_versioned_models.robot
Labels: bug

#374 [#372] Fix RDS engine version and enc. for password
  deploy/ansible/roles/aws_resources/defaults/main.yml
  deploy/ansible/roles/aws_resources/tasks/airflow-rds.yml
  deploy/ansible/roles/legion_enclave/tasks/create_enclave.yml
Labels: bug

#371 [#370] Add Enclave param validation for Cluster's Jenkins
  k8s/jenkins/legion-jenkins-plugin/src/main/resources/legion.groovy
Labels: CI/CD/tests, bug

#366 Remove unused docker and kubernetes labels
  legion/legion/containers/docker.py
  legion/legion/containers/headers.py
  legion/legion/k8s/definitions.py
  legion/legion/k8s/enclave.py
  legion/legion/k8s/properties.py
  legion/legion/k8s/utils.py
  legion/tests/test_k8s.py
Labels: feature

#357 [#323] Legion components authorization tests added
  legion_test/legion_test/robot/utils.py
  tests/robot/0.1_check_components_auth.robot
  tests/robot/0.2_check_clusterwide.robot
  tests/robot/resources/keywords.robot
Labels: CI/CD/tests

#360 [#253] Airflow hook for reading from K8S secrets
  deploy/ansible/roles/legion_enclave/tasks/install_airflow.yml
  deploy/ansible/roles/legion_enclave/templates/airflow-values.yaml.j2
  deploy/helms/airflow/templates/web.yaml
  deploy/helms/airflow/templates/worker-rbac.yaml
  deploy/helms/airflow/templates/worker.yaml
  deploy/helms/airflow/values.yaml
  legion_airflow/legion_airflow/hooks/k8s_base_hook.py
  legion_airflow/legion_airflow/hooks/s3_hook.py
  legion_test/legion_test/robot/airflow.py
Labels: feature

#388 [#387] Remove cheaper, fix incorrect configuration
  legion/legion/templates/docker_files/uwsgi.ini
Labels: feature

#359 [#358] Fixes model_id variable name in 2 tests
  tests/robot/4_check_edi.robot
Labels: CI/CD/tests, bug

#396 [#395] Increase logging in EDI
  legion/legion/edi/server.py
  legion/legion/k8s/enclave.py
Labels: improvement

#384 [#382] Add retries to legionctl tool
  legion/legion/edi/server.py
  legion/legion/external/edi.py
  legion/legion/k8s/enclave.py
  tests/robot/4_check_edi.robot
Labels: feature
