Repository legion-platform/legion, pull requests merged in 2018-05, with the labels that each got.

#46 [#43] Introduce functionality to create/delete enclaves
  deploy/ansible/deploy-legion-enclave.yml
  deploy/ansible/roles/helm/tasks/main.yml
  deploy/ansible/terminate-legion-enclave.yml
  deploy/deploy-legion-enclave.Jenkinsfile
  deploy/profiles/legion-ci.epm.kharlamov.biz.yml
  deploy/profiles/legion-dev.epm.kharlamov.biz.yml
  deploy/profiles/legion-test.epm.kharlamov.biz.yml
  deploy/terminate-legion-enclave.Jenkinsfile
  tests/1_check_airflow.robot
  tests/2_check_models.robot
  tests/load_variables_from_profiles.py
Labels: CI/CD/tests

#67 [#41][#58][#60] Add multi shape support for Kops cluster and addon's improvements
  deploy/ansible/roles/k8s_create_cluster/defaults/main.yaml
  deploy/ansible/roles/k8s_create_cluster/templates/kops.yaml.j2
  deploy/ansible/roles/k8s_resources/tasks/dashboard.yaml
  deploy/ansible/roles/k8s_resources/templates/autoscaler.yaml.j2
  deploy/ansible/roles/k8s_resources/templates/dashboard.ing.yml.j2
  deploy/profiles/legion-ci.epm.kharlamov.biz.yml
  deploy/profiles/legion-dev.epm.kharlamov.biz.yml
  deploy/profiles/legion-test.epm.kharlamov.biz.yml
  examples/Digit-Recognition/Jenkinsfile
  examples/MovieLens/Jenkinsfile
  examples/Sklearn-Income/Jenkinsfile
  examples/Test-Summation/Jenkinsfile
  examples/Vertical-Scaling/performance.Jenkinsfile
  k8s/jenkins/legion-jenkins-plugin/src/main/resources/legion.groovy
  k8s/jenkins/plugins.txt
  tests/2_check_models.robot
Labels: CI/CD/tests, feature, tested

#69 [#55] Jenkins notification filtering based on branch and state transition
  Jenkinsfile
  deploy/create-cluster.Jenkinsfile
  deploy/deploy-legion.Jenkinsfile
  deploy/terminate-cluster.Jenkinsfile
Labels: CI/CD/tests

#72 Removed mistakenly commited chart binaries, updated gitignore
  deploy/.gitignore
  deploy/helms/legion/charts/consul-1.1.3.tgz
  deploy/helms/legion/charts/jupyterhub-v0.5.0.tgz
Labels: feature

#83 [#81] Use correct AWS credentials in robot tests
  deploy/deploy-legion.Jenkinsfile
Labels: bug

#82 [#74] Use specific (not last) version for Jenkins plugin in build process
  Jenkinsfile
  k8s/jenkins/Dockerfile
  k8s/jenkins/legion-jenkins-plugin/pom.xml
  k8s/jenkins/plugins.txt
  k8s/jenkins/scripts/install-plugins.sh
Labels: bug, tested

#86 [#41] Repair code of tests K8S autoscaler
  tests/2_check_models.robot
Labels: bug, tested

#75 [#28] Persistent volume for Jenkins workspace to survive after restarts
  deploy/helms/legion-core/templates/jenkins/jenkins-pvc.yaml
  deploy/helms/legion-core/templates/jenkins/jenkins-server.yaml
  deploy/helms/legion-core/values.yaml
  k8s/jenkins/chmod-docker-and-run-jenkins.sh
  k8s/jenkins/scripts/create_jobs.groovy
Labels: bug, tested

#95 [#57] Implement enclave networkpolicy
  deploy/ansible/roles/legion_chart/tasks/install_enclave.yml
  deploy/ansible/roles/legion_core_chart/tasks/main.yml
  deploy/helms/legion/templates/enclave.networkpolicy.yaml
Labels: feature, tested

#79 [#45] Allow simultanious installation of legion and legion_test
  legion_test/requirements/base.txt
Labels: bug

#104 [#54] Ansible template file names for parallel job execution
  deploy/ansible/roles/k8s_create_cluster/tasks/create-cluster.yaml
  deploy/ansible/roles/k8s_resources/tasks/autoscaler.yaml
  deploy/ansible/roles/k8s_resources/tasks/dashboard.yaml
  deploy/ansible/roles/k8s_resources/tasks/ingress.yaml
  deploy/ansible/roles/k8s_resources/tasks/prometheus.yaml
  deploy/ansible/roles/k8s_resources/tasks/pvc.yaml
  deploy/profiles/legion-ci.epm.kharlamov.biz.yml
  deploy/profiles/legion-demo.epm.kharlamov.biz.yml
  deploy/profiles/legion-dev.epm.kharlamov.biz.yml
  deploy/profiles/legion-test.epm.kharlamov.biz.yml
Labels: CI/CD/tests

#111 Check that all masters are ready before proceeding
  deploy/ansible/roles/k8s_create_cluster/tasks/create-cluster.yaml
  deploy/profiles/legion-demo.epm.kharlamov.biz.yml
Labels: CI/CD/tests, bug

#110 Prometeus installation fails
  deploy/ansible/create-cluster.yml
  deploy/ansible/deploy-legion.yml
  deploy/ansible/roles/helm/tasks/main.yml
Labels: CI/CD/tests, bug

#117 Fix mistype in enclave creation playbook
  deploy/ansible/roles/k8s_resources/tasks/ingress.yaml
  deploy/ansible/roles/legion_enclave/tasks/create_enclave.yml
Labels: bug

#115 [#113] Allow robot tests simultanious run
  legion_test/legion_test/robot/k8s.py
  tests/0_check_clusterwide.robot
  tests/1_check_airflow.robot
  tests/2_check_models.robot
  tests/3_check_flower.robot
  tests/load_variables_from_profiles.py
Labels: CI/CD/tests, bug

#118 [#63] Add livenessprobe and readiness probes
  deploy/ansible/payloads/examine_helm_deployed
  deploy/ansible/roles/charts_common/tasks/main.yml
  deploy/ansible/roles/legion_core_chart/tasks/main.yml
  deploy/ansible/roles/legion_enclave/tasks/install_legion.yml
  deploy/helms/airflow/templates/flower.yaml
  deploy/helms/airflow/templates/mq.yaml
  deploy/helms/airflow/templates/scheduler.yaml
  deploy/helms/airflow/templates/web.yaml
  deploy/helms/legion-core/templates/jenkins/jenkins-server.yaml
  deploy/helms/legion-core/templates/metrics/grafana.yaml
  deploy/helms/legion-core/templates/metrics/graphite.yaml
  deploy/helms/legion/templates/edge/edge-server.yaml
  deploy/helms/legion/templates/edi/edi-server.yaml
  deploy/helms/legion/templates/jupyter/nfs-webserver.yaml
  deploy/helms/legion/templates/metrics/grafana.yaml
  deploy/helms/legion/templates/metrics/graphite.yaml
Labels: CI/CD/tests, feature

#139 [#136] Add refspec for PR builder to Model jobs
  deploy/full-lifecycle.Jenkinsfile
  legion_test/legion_test/templates/jenkins_job.tmpl
  legion_test/legion_test/templates/jenkins_performance_job.tmpl
  tests/1_check_airflow.robot
Labels: CI/CD/tests
