Repository legion-platform/legion, pull requests merged in 2018-12, with the labels that each got.

#630 [#626] Fix nexus ui tests
  legion_test/requirements/base.txt
  tests/robot/resources/browser.robot
  tests/robot/tests/1_common/1.1_check_clusterwide.robot
Labels: QA/Testing, bug

#650 [#101] Remove nginx from the model image
  legion/legion/templates/Dockerfile.tmpl
  legion/legion/templates/docker_files/nginx.conf
  legion/legion/templates/docker_files/supervisord.conf
  legion/legion/templates/docker_files/uwsgi.ini
Labels: improvement, performance

#659 [#658] Update urllib3 and requests due to vulnerability
  base-python-image/Pipfile
  base-python-image/Pipfile.lock
  k8s/edge/Pipfile
  k8s/edge/Pipfile.lock
  legion/requirements/Pipfile
  legion/requirements/Pipfile.lock
  legion_airflow/requirements/Pipfile
  legion_airflow/requirements/Pipfile.lock
  legion_test/requirements/Pipfile
  legion_test/requirements/Pipfile.lock
Labels: security

#570 [#563] API token per model
  deploy/helms/legion/templates/edge/blacklisted-tokens.yaml
  deploy/helms/legion/templates/edge/edge-rbac.yaml
  deploy/helms/legion/templates/edge/invaild-tokens.yaml
  examples/Digit-Recognition/performance/test_basic.py
  examples/Digit-Recognition/tests/test_basic.py
  examples/MovieLens/performance/test_basic.py
  examples/Sklearn-Income/performance/test_basic.py
  examples/Sklearn-Income/tests/test_basic.py
  examples/Test-Summation/performance/test_basic.py
  examples/Test-Summation/tests/test_basic.py
  k8s/edge/Dockerfile
  k8s/edge/blacklisted_tokens.lua
  k8s/edge/nginx.conf.ltmpl
  legion/legion/edi/server.py
  legion/legion/external/edi.py
  legion/legion/http.py
  legion/legion/template_plugins/k8s.py
  legion_test/legion_test/robot/utils.py
  tests/robot/resources/keywords.robot
  tests/robot/tests/1_common/1.0_check_components_auth.robot
  tests/robot/tests/2_jenkins_models/2.0_check_jenkins_models.robot
  tests/robot/tests/3_edi_one_model/3.0_check_edi_one_model.robot
Labels: feature

#663 [#474] parallelization of the unit tests
  Jenkinsfile
  legion/docs/source/testing.md
  legion/requirements/Pipfile
  legion/requirements/Pipfile.lock
  legion/tests/test_base_io_operations.py
  legion/tests/test_deploy.py
  legion/tests/test_edi.py
  legion/tests/test_k8s.py
  legion/tests/test_metrics.py
  legion/tests/test_model_client.py
  legion/tests/test_pyserve.py
  legion/tests/test_types.py
  legion/tests/test_utils_external_file.py
  legion/tests/test_utils_other.py
  legion/tests/test_utils_text_operations.py
Labels: CI/CD/tests

#662 [#367] Add tests for incorrect legionctl usage
  Jenkinsfile
  legion/bin/legionctl
  legion/legion/edi/deploy.py
  legion/legion/external/edi.py
  legion/legion/k8s/utils.py
  legion/legion/pymodel/model.py
  legion/tests/test_legionctl.py
  legion/tests/test_utils_external_file.py
  tests/robot/load_variables_from_profiles.py
  tests/robot/resources/keywords.robot
  tests/robot/resources/variables.robot
  tests/robot/tests/6_incorrect_legionctl_commands/6.1_check_incorrect_legionctl_commands.robot
Labels: CI/CD/tests

#665 [#664] pylint upgrade
  Jenkinsfile
  k8s/edge/Pipfile
  k8s/edge/Pipfile.lock
  legion/requirements/Pipfile
  legion/requirements/Pipfile.lock
  legion_airflow/requirements/Pipfile
  legion_airflow/requirements/Pipfile.lock
  legion_test/requirements/Pipfile
  legion_test/requirements/Pipfile.lock
Labels: WIP

#701 [#700] add missed braces
  deploy/build-and-deploy-legion.Jenkinsfile
Labels: critical

#669 [#666] Rename version to model_version
  k8s/edge/nginx.conf.ltmpl
  legion/legion/edi/server.py
  legion/legion/external/edi.py
  tests/robot/resources/keywords.robot
  tests/robot/tests/2_jenkins_models/2.0_check_jenkins_models.robot
  tests/robot/tests/3_edi_one_model/3.0_check_edi_one_model.robot
Labels: critical

#698 [#697] add post cleanup stage
  deploy/ci.Jenkinsfile
  tests/robot/tests/3_edi_one_model/3.0_check_edi_one_model.robot
Labels: critical

#680 [#679] Add changelog notes for 0.10.0 release
  CHANGELOG.md
Labels: improvement
