Repository legion-platform/legion, pull requests merged in 2018-06, with the labels that each got.

#158 [#157] Fix documentation publishing process
  Jenkinsfile
Labels: CI/CD/tests, bug

#172 [#152] Production ready serving for edi
  deploy/helms/legion/templates/edi/edi-server.yaml
  k8s/edi/Dockerfile
  k8s/edi/app_uwsgi.ini
  k8s/edi/chmod-docker-and-run-edi.sh
  k8s/edi/nginx.conf
  k8s/edi/supervisord.conf
  k8s/edi/uwsgi.ini
  legion/legion/edi/wsgi.py
Labels: CI/CD/tests, bug

#173 [#96] Model batch invocation
  legion/analyze_code.sh
  legion/legion/http.py
  legion/legion/model/client.py
  legion/legion/serving/pyserve.py
  legion/tests/legion_test_utils.py
  legion/tests/test_pyserve.py
Labels: bug, feature

#190 [#189] Added legion python package to Airflow
  deploy/ansible/roles/legion_enclave/templates/airflow-values.yaml.j2
  deploy/helms/airflow/templates/worker.yaml
  deploy/helms/airflow/values.yaml
  k8s/airflow/Dockerfile
Labels: feature

#176 [#191] Ansible-vault legion s3 integration
  deploy/ansible/create-cluster.yml
  deploy/ansible/deploy-legion-enclave.yml
  deploy/ansible/deploy-legion.yml
  deploy/ansible/terminate-legion-enclave.yml
  deploy/legionPipeline.groovy
  deploy/profiles/legion-ci.epm.kharlamov.biz.yml
  deploy/profiles/legion-demo.epm.kharlamov.biz.yml
  deploy/profiles/legion-dev.epm.kharlamov.biz.yml
  deploy/profiles/legion-test.epm.kharlamov.biz.yml
Labels: feature
