Repository legion-platform/legion, pull requests merged in 2018-09, with the labels that each got.

#414 [#412] Fixes Jenkins Robot tests for the Sklearn-income model
  examples/Sklearn-Income/Jenkinsfile
  examples/Sklearn-Income/tests/test_basic.py
  tests/robot/2_check_models.robot
Labels: CI/CD/tests, bug, critical

#417 [#416] Airflow test checks only test dags
  tests/robot/1_check_airflow.robot
Labels: CI/CD/tests, bug, critical

#391 [#327] Secure prometheus ingress components
  deploy/ansible/roles/k8s_resources/templates/prometheus.yml.j2
Labels: feature

#405 [#404] Return build description
  Jenkinsfile
Labels: CI/CD/tests

#389 [#112] Add Kube ELB security plugin deployment
  deploy/ansible/roles/k8s_resources/tasks/kube-elb-security.yaml
  deploy/ansible/roles/k8s_resources/tasks/main.yml
  deploy/helms/kube-elb-security/.helmignore
  deploy/helms/kube-elb-security/Chart.yaml
  deploy/helms/kube-elb-security/templates/_helpers.tpl
  deploy/helms/kube-elb-security/templates/deployment.yaml
  deploy/helms/kube-elb-security/templates/rbac.yaml
  deploy/helms/kube-elb-security/values.yaml
Labels: feature

#427 [#422] Update dex groups mapping
  deploy/ansible/roles/k8s_resources/tasks/cluster-groups.yaml
  deploy/ansible/roles/legion_core_chart/templates/legion-core-values.yaml.j2
  deploy/ansible/roles/legion_enclave/templates/airflow-values.yaml.j2
  deploy/profiles/secrets_template.yaml
  legion_airflow/legion_airflow/auth/dex_auth.py
Labels: critical, security

#421 [#420] Model test expected result fixed
  tests/robot/5_check_edi_multi_versioned_models.robot
Labels: CI/CD/tests, bug, critical

#380 [#379] Fixes incorrect auth urls for components security check
  legion_test/legion_test/robot/utils.py
  tests/robot/resources/keywords.robot
Labels: CI/CD/tests, bug

#426 [#425] Edi test timeouts increased for the debugging in error cases
  tests/robot/4_check_edi.robot
  tests/robot/5_check_edi_multi_versioned_models.robot
Labels: CI/CD/tests, bug, critical

#418 [#408] Return model service after creation
  legion/legion/k8s/enclave.py
Labels: bug, critical

#429 [#428] Add timed out processes log gathering in Robot tests
  deploy/legionPipeline.groovy
  legion_test/legion_test/process_reporter.py
Labels: CI/CD/tests, bug, critical

#409 [#406] Add symlink in model pods
  legion/legion/containers/docker.py
  legion/legion/templates/Dockerfile.tmpl
  legion/tests/legion_test_utils.py
  legion/tests/test_deploy.py
  legion/tests/test_models/complex_model/run.py
Labels: critical, feature

#435 [#434] Add timeouts in robot processor, fix logging, increase verbosity
  legion/legion/edi/deploy.py
  legion/legion/external/edi.py
  legion_test/legion_test/process_reporter.py
Labels: critical, improvement

#442 [#441] Added cffi apk package for Edge docker image
  k8s/edge/Dockerfile
Labels: bug, critical

#437 [#436] Unburstable EC2 instances
  deploy/profiles/legion-ci.epm.kharlamov.biz.yml
  deploy/profiles/legion-demo.epm.kharlamov.biz.yml
  deploy/profiles/legion-dev.epm.kharlamov.biz.yml
  deploy/profiles/legion-test.epm.kharlamov.biz.yml
Labels: CI/CD/tests, WIP

#449 [#37] Remove old grafana code
  legion/legion/serving/pyserve.py
Labels: improvement

#460 [#455] Locked Jenkins version to 2.121.3
  k8s/jenkins/Dockerfile
Labels: bug, critical

#453 [#452] Update flask version to 0.12.4
  base-python-image/requirements.txt
  k8s/test-bare-model-api/model-1/requirements.txt
  k8s/test-bare-model-api/model-2/requirements.txt
  legion/requirements/base.txt
Labels: improvement

#465 [#464] Add pandas to EDGE Dockerfile
  k8s/edge/Dockerfile
Labels: CI/CD/tests, improvement

#440 [#438] Fix accessing unknown deployments
  Jenkinsfile
  legion/analyze_code.sh
  legion/legion/k8s/definitions.py
  legion/legion/k8s/services.py
  legion/legion/utils.py
  legion/tests/test_utils_other.py
Labels: bug, critical

#444 [#443] Modified Airflow worker permissions to enable ConfigMap creation
  deploy/helms/airflow/templates/worker-rbac.yaml
Labels: improvement

#289 [#285] Model properties change notification
  deploy/helms/legion/templates/model-rbac.yaml
  examples/Test-Summation/Summation.ipynb
  examples/Test-Summation/store.py
  k8s/jenkins/legion-jenkins-plugin/src/main/resources/legion.groovy
  legion/docs/source/rbac.md
  legion/legion/containers/docker.py
  legion/legion/k8s/enclave.py
  legion/legion/k8s/properties.py
  legion/legion/k8s/watch.py
  legion/legion/model/__init__.py
  legion/legion/pymodel/model.py
  legion/legion/serving/pyserve.py
  legion/legion/templates/Dockerfile.tmpl
  legion/legion/templates/docker_files/supervisord.conf
  legion/legion/templates/docker_files/uwsgi.ini
  legion/legion/utils.py
  legion/tests/test_deploy.py
  legion/tests/test_models/complex_model/complex_package/store.py
  legion/tests/test_models/complex_model/run.py
  legion/tests/test_utils_other.py
  legion_test/bin/jenkins_dex_client
  legion_test/legion_test/robot/__init__.py
  legion_test/legion_test/robot/dex_client.py
  legion_test/legion_test/robot/grafana.py
  legion_test/legion_test/robot/jenkins.py
  legion_test/legion_test/robot/k8s.py
  legion_test/legion_test/robot/model.py
  legion_test/legion_test/utils.py
  tests/python/test_k8s_properties_storages.py
  tests/robot/2_check_models.robot
  tests/robot/resources/keywords.robot
  tests/robot/resources/variables.robot
Labels: critical, feature

#483 [#383] Add Run Process without PIPE action to Robot Tests
  legion_test/legion_test/process_reporter.py
  legion_test/legion_test/profiler_loader.py
  legion_test/legion_test/robot/__init__.py
  legion_test/legion_test/robot/framework_extensions.py
  legion_test/legion_test/robot/process.py
  tests/robot/4_check_edi.robot
  tests/robot/5_check_edi_multi_versioned_models.robot
  tests/robot/resources/keywords.robot
Labels: bug

#495 [#485] Update durable-task plugin
  k8s/jenkins/plugins.txt
Labels: bug

#502 [#501] Pin ipykernel==4.9.0
  base-python-image/requirements.txt
Labels: CI/CD/tests, bug, critical
